AuthSystem/Controllers/AssignmentController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AssignmentManagement.PayPalHelper;
using AuthSystem.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;


namespace AuthSystem.Controllers
{
    [Authorize]
    public class AssignmentController : Controller
    {
        private readonly AssignmentContext _context;
        private IWebHostEnvironment _hostingEnvironment;
        private IConfiguration _configuration { get; }
        public AssignmentController(AssignmentContext context, IWebHostEnvironment webHostEnvironment,  IConfiguration configuration)
        {
            _context = context;
            _hostingEnvironment = webHostEnvironment;
            _configuration = configuration;
        }

        // GET: Assignment Applications
        public async Task<IActionResult> Index()
        {
            var user = await _context.Users.FirstOrDefaultAsync(x => x.Email == User.Identity.Name);

            return View(_context.AssignmentApplications.Where(x => x.ApplicationUser.Id == user.Id));
        }

        // GET: Employees/Create
        public IActionResult AddOrEdit(int id = 0)
        {
            if (id == 0)
                return View(new AssignmentApplication());

            return View(_context.AssignmentApplications.Find(id));
        }

        // POST: Employees/Create
        // To protect from overposting attacks, enable the specific properti es you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOrEdit([Bind("AssignmentId,Institution,Course,Year,DueDate,AdditionalNotes")] AssignmentApplication assignmentApplication, IFormFile postedFile)
        {
            if (ModelState.IsValid)
            {
                string uploads = Path.Combine(_hostingEnvironment.WebRootPath, "Docs");
                string filePath = Path.Combine(uploads, postedFile.FileName);
                using (Stream fileStream = new FileStream(filePath, FileMode.Create))
                {
                    await postedFile.CopyToAsync(fileStream);
                }

                assignmentApplication.FileName = postedFile.FileName;
                var username = User.Identity.Name;
                assignmentApplication.ApplicationUser = _context.Users.FirstOrDefault(x => x.Email == username);
                if (assignmentApplication.AssignmentId == 0)
                {
                    assignmentApplication.Status = "Submitted";
                    assignmentApplication.Amount = 1000;
                    _context.Add(assignmentApplication);
                }
                else
                {
                    _context.Update(assignmentApplication);
                }

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(assignmentApplication);
        }



        // GET: Employees/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            var employee = await _context.AssignmentApplications.FindAsync(id);
            _context.AssignmentApplications.Remove(employee);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Checkout(double Amount)
        {
            
            Amount = 1; 
            var payPalApi = new PayPalAPI(_configuration);
            string url = await payPalApi.getRedirectURLToPayPal();
            return Redirect(url);
        }

       
        public async Task<IActionResult> Success()
        {
            //var payPalApi = new PayPalAPI(_configuration);
            //PayPalPaymentExecutedResponse result = await payPalApi.executePayment(paymentId, PlayerID);

            // var user = await _context.Users.FirstOrDefaultAsync(x=>x.Email == User.Identity.Name);
            var application = await _context.AssignmentApplications.FirstOrDefaultAsync(x => x.ApplicationUser.Email == User.Identity.Name); //TODO this will only work if the user has one applications
            application.Status = "Paid";
            application.Amount = 1;
            _context.Update(application);
           
           return RedirectToAction(nameof(Index));
        }
    }
}

AuthSystem/Views/Shared/Index.cshtml
@model IEnumerable<AuthSystem.Models.AssignmentApplication>

@{
    ViewData["Title"] = "Index";
}

<h4>Assignment Applications</h4>
<hr />

<div class="container">
    <table class="table table-hover">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Institution)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Course)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DueDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.AdditionalNotes)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Status)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Amount)
                </th>
                <th>
                    <a asp-action="AddOrEdit" class="btn btn-outline-success"><i class="far fa-plus-square"></i> Assignment Application</a>
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Institution)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Course)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DueDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AdditionalNotes)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    R  @Html.DisplayFor(modelItem => item.Amount)
                </td>
                <td>
                    <a asp-action="AddOrEdit" asp-route-id="@item.AssignmentId"><i class="fa fa-marker fa-lg"></i></a> |
                    <a asp-action="Delete" asp-route-id="@item.AssignmentId" class="text-danger" ml-1 onclick="return confirm('Are you sure to delete this record')"><i class="fa fa-trash-alt fa-lg"></i></a> |
                    <a asp-action="Checkout" asp-route-id="@item.Amount"> <i class="fab fa-paypal" aria-hidden="true"> Pay With PayPal</i> </a>
                </td>
            </tr>
}
        </tbody>
    </table>
</div>

AuthSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>IT Assignments Buddy</title>
  <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
  <link rel="stylesheet" href="~/css/site.css" />
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
              <a class="navbar-brand" asp-area="" asp-controller="Assignment" asp-action="Index">IT Assignment Buddy</a>
                
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial.cshtml" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            &copy; 2021 - Soulful Soulutions - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>